/** @format */

import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "irankidz",
  description: "Generated by create next app",
  icons: "./images/irankidz.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
